source 'https://rubygems.org'

gem 'mongoid'
gem 'mongoid-paperclip'
gem 'ish_models'
gem 'cancancan'
gem 'kaminari'
gem 'kaminari-mongoid'
gem 'kaminari-actionview'
gem 'devise'
gem 'aws-sdk'

# for travis dependencies
gem 'i18n', '0.8.1'
gem 'minitest', '5.10.2'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'simplecov'
end
