#!/bin/bash

set -ex

if ! (( ssh-add -L | grep mac_id_rsa )) ; then
  ssh-add ~/.ssh/mac_id_rsa
fi

./scripts/version_bump

bundle

gem build ishapi.gemspec
gem push ishapi-`cat VERSION`.gem

git add .
git commit -m 'autobuild `date "+%Y%m%d"`'
git push

echo "ishapi build ok"

