#!/bin/bash

set -ex

if ! (( ssh-add -L | grep mac_id_rsa_2 )) ; then
  ssh-add ~/.ssh/mac_id_rsa_2
fi

./scripts/version_bump

bundle

version=`cat VERSION`
echo $version

cat ishapi.gemspec-template | \
  sed -e "s/\$version/$version/g" > ishapi.gemspec

gem build ishapi.gemspec
gem push ishapi-$version.gem

git add .
git commit -m 'autobuild `date "+%Y%m%d"`'
git push

echo "ishapi build ok"

